export enum ApplyType {
    HealthSuperficial,
    WillpowerSuperficial,
    HealthAggravated,
    WillpowerAggravated,
    Hunger,
    Humanity,
    Stains,
    Experience,
    Advantage,
    Flaw,
    SpecialtyPhysical,
    SpecialtySocial,
    SpecialtyMental,
}